use super::*;

pub use linux5_13::{
    UFFDIO_API, UFFDIO_CONTINUE, UFFDIO_CONTINUE_MODE_DONTWAKE, UFFDIO_COPY,
    UFFDIO_COPY_MODE_DONTWAKE, UFFDIO_COPY_MODE_WP, UFFDIO_REGISTER, UFFDIO_REGISTER_MODE_MINOR,
    UFFDIO_REGISTER_MODE_MISSING, UFFDIO_REGISTER_MODE_WP, UFFDIO_UNREGISTER, UFFDIO_WAKE,
    UFFDIO_WRITEPROTECT, UFFDIO_WRITEPROTECT_MODE_DONTWAKE, UFFDIO_WRITEPROTECT_MODE_WP,
    UFFDIO_ZEROPAGE, UFFDIO_ZEROPAGE_MODE_DONTWAKE, UFFD_API, UFFD_API_IOCTLS,
    UFFD_API_RANGE_IOCTLS, UFFD_API_RANGE_IOCTLS_BASIC,
};

pub const UFFD_API_FEATURES: u64 = linux5_13::UFFD_API_FEATURES | UFFD_FEATURE_WP_UNPOPULATED;
